---
title: "dartboard_images"
output: html_document
---

# Make tables
```{r}
df <- data.frame(
  variable = c("in", "out"),
  value = c(1, 5, 2, 4, 3, 3, 4, 2, 5, 1),
  board=c(rep("5/6", 2),
          rep("4/6", 2),
          rep("3/6", 2),
          rep("2/6", 2),
          rep("1/6", 2)))

df_1 = filter(df, board == "1/6")
df_2 = filter(df, board == "2/6")
df_3 = filter(df, board == "3/6")
df_4 = filter(df, board == "4/6")
df_5 = filter(df, board == "5/6")
```

# Plot
```{r}

ggplot(df_1, aes(x = "", y = value, fill = variable)) +
  geom_col(width = 1) +
  scale_fill_manual(values = c("red", "yellow")) +
  coord_polar() +
  theme_minimal() +
  scale_fill_manual(values=c("gray","blue")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill=FALSE)

ggplot(df_2, aes(x = "", y = value, fill = variable)) +
  geom_col(width = 1) +
  scale_fill_manual(values = c("red", "yellow")) +
  coord_polar() +
  theme_minimal() +
  scale_fill_manual(values=c("gray","blue")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill=FALSE)

ggplot(df_3, aes(x = "", y = value, fill = variable)) +
  geom_col(width = 1) +
  scale_fill_manual(values = c("red", "yellow")) +
  coord_polar() +
  theme_minimal() +
  scale_fill_manual(values=c("gray","blue")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill=FALSE)

ggplot(df_4, aes(x = "", y = value, fill = variable)) +
  geom_col(width = 1) +
  scale_fill_manual(values = c("red", "yellow")) +
  coord_polar() +
  theme_minimal() +
  scale_fill_manual(values=c("gray","blue")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill=FALSE)

ggplot(df_5, aes(x = "", y = value, fill = variable)) +
  geom_col(width = 1) +
  scale_fill_manual(values = c("red", "yellow")) +
  coord_polar() +
  theme_minimal() +
  scale_fill_manual(values=c("gray","blue")) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill=FALSE)
```
